### ISSUE TITLE
PhantomX reactor

### ISSUE THREAD

**Issue by kingstone1927** [yoshimalucky/dynamixel_workbench_ros_control#6]
Hello,

This is Thach. I am working on a research project where I need to control a robotic arm that uses dynamixel servos. Could anyone with ROS expertise help me troubleshoot the issue? We can set up a zoom call, and I can show the error. Thanks!

Email: nguy75512@stthomas.edu
Name: Thach Nguyen

**Comment by robograffitti** [comment]
Hi, Thanks for your contact. 

I do not have time to set up a zoom session. Could you please paste your screen shot?

And, make sure that I can not help your personal project but an issue related to this repository.

**Comment by kingstone1927** [comment]
Hey @robograffitti
Thanks for the quick response! I am using these followings repo to control a PhantomX Reactor arm and got this error. I have ROS Noetic and Ubuntu 20.4 on my machine.
https://github.com/arebgun/dynamixel_motor
https://github.com/RobotnikAutomation/phantomx_reactor_arm/blob/indigo-devel/README.md


![image](https://user-images.githubusercontent.com/34840066/153916258-bcb96e9c-89d9-4d1d-aa07-6b8290449dc9.png)

**Comment by robograffitti** [comment]
Don't post an issue not related to this repository, please.

I'm neither a member of Robotonik Automation nor a maintainer of PhantomX reactor arm.

Email them:
https://github.com/RobotnikAutomation/phantomx_reactor_arm/blob/indigo-devel/phantomx_reactor_arm/package.xml
